### ISSUE TITLE
not able to running t5 inference script

### ISSUE THREAD

**Issue by shankyemcee** [thu-coai/JointGT#2]
When I run bash infer_jointgt_t5.sh this error is coming:

12/27/2021 02:08:29 - INFO - __main__ - Namespace(adam_epsilon=1e-08, append_another_bos=False, checkpoint=None, clean_up_spaces=False, dataset='webnlg', debug=False, do_lowercase=False, do_predict=True, do_pretrain=False, do_train=Fa>
12/27/2021 02:08:29 - INFO - __main__ - jointgt_t5
12/27/2021 02:08:29 - INFO - __main__ - Using 1 gpus
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - Model name 'jointgt_t5' not found in model shortcut name list (t5-small, t5-base, t5-large, t5-3b, t5-11b). Assuming 'jointgt_t5' is a path, a model identifier, or ur>
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - Didn't find file jointgt_t5/added_tokens.json. We won't load it.
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - Didn't find file jointgt_t5/special_tokens_map.json. We won't load it.
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - Didn't find file jointgt_t5/tokenizer_config.json. We won't load it.
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - loading file jointgt_t5/spiece.model
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - loading file None
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - loading file None
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - loading file None
12/27/2021 02:08:29 - INFO - transformers.tokenization_utils_base - loading file jointgt_t5/tokenizer.json
12/27/2021 02:08:30 - INFO - transformers.configuration_utils - loading configuration file jointgt_t5/config.json
12/27/2021 02:08:30 - INFO - transformers.configuration_utils - Model config T5Config {
  "architectures": [
    "MyT5Pretrain"
  ],
  "d_ff": 3072,
  "d_kv": 64,
  "d_model": 768,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "eos_token_id": 1,
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "layer_norm_epsilon": 1e-06,
  "model_type": "t5",
  "n_positions": 512,
  "num_heads": 12,
  "num_layers": 12,
  "output_past": true,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "task_specific_params": {
    "summarization": {
      "early_stopping": true,
      "length_penalty": 2.0,
      "max_length": 200,
      "min_length": 30,
      "no_repeat_ngram_size": 3,
      "num_beams": 4,
      "prefix": "summarize: "
    },
    "translation_en_to_de": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to German: "
    },
    "translation_en_to_fr": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to French: "
    },
    "translation_en_to_ro": {
      "early_stopping": true,
      "max_length": 300,
      "num_beams": 4,
      "prefix": "translate English to Romanian: "
    }
  },
  "vocab_size": 32128
}

12/27/2021 02:08:30 - INFO - transformers.modeling_utils - loading weights file jointgt_t5/pytorch_model.bin
12/27/2021 02:08:44 - INFO - transformers.modeling_utils - All model checkpoint weights were used when initializing MyT5ForConditionalGeneration.

12/27/2021 02:08:44 - INFO - transformers.modeling_utils - All the weights of MyT5ForConditionalGeneration were initialized from the model checkpoint at jointgt_t5.
If your task is similar to the task the model of the ckeckpoint was trained on, you can already use MyT5ForConditionalGeneration for predictions without further training.
12/27/2021 02:08:44 - INFO - __main__ - Loading checkpoint from jointgt_t5
Output directory () already exists and is not empty.
Total samples = 12876
Total samples = 1600
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
/project/6027213/shankar5/envs/jointgt/lib/python3.7/site-packages/transformers/modeling_utils.py:1500: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0>
  beam_id = beam_token_id // vocab_size
12/27/2021 02:19:42 - INFO - __main__ - Saved prediction in jointgt_t5/test_beam5_lenpen1_predictions.txt
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
PTBTokenizer tokenized 99305 tokens at 190017.25 tokens per second.
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
Picked up JAVA_TOOL_OPTIONS: -Xmx2g
PTBTokenizer tokenized 8777 tokens at 29353.41 tokens per second.
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
Running MS-COCO evaluator...
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
tokenization...
setting up scorers...
computing Bleu score...
Bleu_1: 0.0007
Bleu_2: 0.0006
Bleu_3: 0.0004
Bleu_4: 0.0003
computing METEOR score...
{'testlen': 7060, 'reflen': 29091, 'guess': [7060, 5492, 5231, 4999], 'correct': [117, 64, 27, 13]}
ratio: 0.24268674160392414
Traceback (most recent call last):
  File "cli_gt.py", line 134, in <module>
    main()
  File "cli_gt.py", line 130, in main
    run(args, logger)
  File "/project/6027213/shankar5/envs/jointgt/JointGT/run_gt.py", line 88, in run
ems = inference(model, dev_dataloader, tokenizer, args, logger, save_predictions=True)
  File "/project/6027213/shankar5/envs/jointgt/JointGT/run_gt.py", line 285, in inference
    return evaluate_bleu(data_ref=data_ref, data_sys=predictions)
  File "/project/6027213/shankar5/envs/jointgt/JointGT/data.py", line 973, in evaluate_bleu
    coco_eval = run_coco_eval(data_ref, data_sys)
  File "/project/6027213/shankar5/envs/jointgt/JointGT/data.py", line 32, in run_coco_eval
    coco_eval.evaluate()
  File "/project/6027213/shankar5/envs/jointgt/JointGT/eval_webnlg/pycocoevalcap/eval.py", line 55, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/project/6027213/shankar5/envs/jointgt/JointGT/eval_webnlg/pycocoevalcap/meteor/meteor.py", line 39, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/project/6027213/shankar5/envs/jointgt/JointGT/eval_webnlg/pycocoevalcap/meteor/meteor.py", line 59, in _stat
    self.meteor_p.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

**Comment by kepei1106** [comment]
Hi, it seems that this error comes from the evaluation script of METEOR. It may be due to some corner cases in the generated results (such as empty lines). I find that there may exist some problems in the generated results because the BLEU score is too low. Thus, I suggest that you should first check the generated results in jointgt_t5/test_beam5_lenpen1_predictions.txt and make sure whether the checkpoint saved in the training process is reliable. If not, you may further check the log during training.

**Comment by shankyemcee** [comment]
Hi Thanks for your reply. I am using the configurations as shown in the steps for running  infer_jointgt_t5.sh so I dont understand why it is not working. I have attached a zip of the data folder which I downloaded from the drive link: https://drive.google.com/drive/folders/1FGThWaTUs1cLvkd_GHCFV8mQEDW6qfIK. Could it be something to do with the java installation? It appears java is required to run meteor script.


[webnlg.zip](https://github.com/thu-coai/JointGT/files/7919138/webnlg.zip)

**Comment by kepei1106** [comment]
The evaluation script is adapted from https://github.com/wenhuchen/Data-to-text-Evaluation-Metric. The requirements may include Java 1.8 in addition to python.
From the log you provide, the data have been successfully loaded. I still recommend to check the generated results in the output file. Note that our released checkpoint is the pre-trained model. You should fine-tune this model on the downstream datasets such as WebNLG before inference.

**Comment by shankyemcee** [comment]
Thanks I am trying to run fine tuning now. It appears to work when I remove the meteor score calculation. Also I would like to run this model on my own dataset but I dont see any preprocessing steps for the data files. Are these steps available?

**Comment by kepei1106** [comment]
We adopt the data format of KGPT (https://github.com/wenhuchen/KGPT) and directly use part of their pre-processed data such as WebNLG. You can refer to the paper and repository of KGPT to pre-process your own dataset.

**Comment by shankyemcee** [comment]
Thanks for the help !

**Comment by ZhaozwTD** [comment]
I run the **_finetune_jointgt_bart.sh_** and also encounter the problem of "BrokenPipeError: [Errno 32] Broken pipe". Following the guidance in https://github.com/InnerPeace-Wu/densecap-tensorflow/issues/10, I run this script successfully. Simply, place this [file](https://github.com/lichengunc/refer/tree/master/evaluation/meteor/data) in JointGT-main/eval_webnlg/pycocoevalcap/meteor/data/. It is not yet clear how this will affect the final results.
